server:
  port: 8081
spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: rabbitmq
    password: wgf123
    publisher-confirm-type: correlated  # 发布消息成功到交换器后会触发回调方法
    listener:
      simple:
        prefetch: 5
        #acknowledge-mode: manual  # 手动ack模式