server:
  port: 8081
spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: wgf
    password: wgf123
    publisher-confirm-type: correlated  # 发布消息成功到交换器后会触发回调方法
    listener:
      simple:
        prefetch: 5
#        acknowledge-mode: manual  # 手动ack模式
#        retry:
#          enabled: true
#          max-attempts: 5       # 最大重试次数
#          max-interval: 10000   # 重试最大间隔时间
#          initial-interval: 2000  # 重试初始间隔时间
#          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
#        default-requeue-rejected: false  # 重试次数超过上面的设置之后是否丢弃